services:
  ## Postgres for applications
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: confdashweb
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

    restart: unless-stopped
  ## Keycloack
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    command: [ "start-dev", "--import-realm", "--http-port=8181"]

    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: confdashweb
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8181"
    restart: unless-stopped
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - postgres


  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"


networks:
  postgres:
    driver: bridge

