server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/abstracts
    username: confdashweb
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          client-id: spring-cloud-client
          jwk-set-uri: http://localhost:8181/realms/confdashweb/protocol/openid-connect/certs
          issuer-uri: http://localhost:8181/realms/confdashweb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/