server:
  port: 8080


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/confdashweb
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://keycloak:8080/realms/confdashweb
            user-name-attribute: email
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak-provider
            scope: openid
            client-id: spring-cloud-client
            client-secret: 4F7tSNbGYBIvAnNPSESeBjxYHO2Grvch
            authorization-grant-type: authorization_code
            redirect-uri: http://keycloak:8080/login/oauth2/code/keycloak
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/