server:
  port: 8081
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    password: password
    username: confdashweb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

#eureka:
#  client:
#    service-url:
#      {http://localhost:8761/eureka}
