server:
  port: 8085
spring:
  application:
    name: siteManagementService
  datasource:
    username: confdashweb
    password: password
    url: jdbc:postgresql://localhost:5432/site
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true