server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/events
    username: confdashweb
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/confdashweb
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/