server:
  port: 0
spring:
  application:
    name: event-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    password: password
    username: confdashweb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8181/realms/confdashweb
          jwk-set-uri: http://localhost:8181/realms/confdashweb/protocol/openid-connect/certs

#      client:
#        provider:
#          keycloak-provider:
#            issuer-uri: http://localhost:8181/realms/confdashweb
#        registration:
#          keycloak-spring-gateway-client:
#            provider: keycloak-provider
#            scope: openid
#            client-id: spring-cloud-client
#            client-secret: eIEAsftRLNv8hk9FX1L9OR3jtaSqkIqe
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
#Resiliance4j Proprieties
resilience4j:
  circuitbreaker:
    instances:
      event-cals:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - java.lang.IllegalArgumentException
  timelimiter:
    instances:
      event-cals:
        timeout-duration: 5s
  retry:
    instances:
      event-cals:
        max-attempts: 3
        wait-duration: 5s
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


